# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lahni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInput', models.CharField(max_length=255)),
                ('output', models.CharField(blank=True, max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='actionType',
            field=models.CharField(choices=[('chef', 'recipeRecommendation')], default='chef', max_length=50),
        ),
        migrations.AddField(
            model_name='action',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructions',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='instructions',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructions',
            name='intentID',
            field=models.CharField(default=12345678, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='audio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='media',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='steps',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='message',
            field=models.CharField(default='This is a force step', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steps',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='lahni.Instructions'),
        ),
    ]
